version: "2"
linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true